version: "3.9"

services:
  users:
    build: ./users
    container_name: users_service
    ports:
      - "8001:8000"

  orders:
    build: ./orders
    container_name: orders_service
    ports:
      - "8002:8000"
    environment:
      USERS_SERVICE_URL: "http://users:8000"
    depends_on:
      - users
